version: '3.1'
services:
    nginx:
        build:
            context: ./Proxy/
            dockerfile: Dockerfile
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./Proxy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./Backend/html:/var/www/
            - ./data:/etc/nginx/certs
        networks:
            - my-network
        ports:
            - "80:80"
            - "443:443"
    flask:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        image: flask:0.0.1
        container_name: flask
        volumes:
        - ./:/code/
        environment:
                - FLASK_APP=/code/Backend/code/main.py
        command: flask run --host=0.0.0.0
        networks:
             my-network:
                 aliases:
                    - flask-app
          
   # mysql-development:
    #    build:
     #       context: ./Database
      #      dockerfile: ./Dockerfile

networks:
    my-network:
            


