version: '3.1'
services:
    nginx:
        build:
            context: ./Proxy/
            dockerfile: ./Dockerfile
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./Proxy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./Backend/html:/var/www/
            - ./data:/etc/nginx/certs
        networks:
            - my-network
        ports:
            - "80:80"
            - "443:443"
    flask:
        build:
            context: ./Backend/
            dockerfile: ./Dockerfile
        container_name: flask
        volumes:
        - ./:/code/
        environment:
                - FLASK_APP=/code/Backend/code/main.py
        command: flask run --host=0.0.0.0 --debugger
        networks:
            db-network:
            my-network:
                aliases:
                    - flask-app
          
    db:
        build:
            context: ./Database/
            dockerfile: ./Dockerfile 
        networks:
            - db-network
volumes:
    my-db:

networks:
    my-network:
    db-network:
            


