version: '3.1'
services:
    nginx:
        build:
            context: ./Proxy
            dockerfile: ./Dockerfile
        container_name: nginx4
        depends_on:
            - flask
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
        ports:
            - 90:80
    flask:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        image: flask:0.0.1
        container_name: flask
        command: flask run --host=0.0.0.0
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
        MYSQL_ROOT_PASSWORD: example

  adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

networks:
    my-network:


